[package]
name = "p2p"
version = "0.1.0"
authors = ["Johann Og <kronolynx@gmail.com>"]

[dependencies]
bytes = "0.4.10"
futures = "0.1.24"
getopts = "0.2.18"
rand = "0.5.5"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.30"
tokio = "0.1.11"
tokio-codec = "0.1.0"
